import React, { useCallback, useState } from "react";
import {
  ActivityIndicator, Alert, FlatList, KeyboardAvoidingView, Platform,
  RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput,
  TouchableOpacity, View,
} from "react-native";
import { useFocusEffect } from "expo-router";
import { createDoctor, deleteDoctor, getDoctors, restoreDoctor, updateDoctor } from "../api/api";

const initial = {
  name:"",email:"",phone:"",password:"",specialization:"",qualification:"",
  licenseNumber:"",experience:"0",consultationFee:"0",availableDays:[] as string[],
  startTime:"09:00",endTime:"17:00",department:"",bio:""
};
const days=[["Mon","monday"],["Tue","tuesday"],["Wed","wednesday"],["Thu","thursday"],["Fri","friday"],["Sat","saturday"],["Sun","sunday"]];

export default function Doctors(){
  const [items,setItems]=useState<any[]>([]); const [form,setForm]=useState<any>(initial);
  const [editing,setEditing]=useState<any>(null); const [show,setShow]=useState(false);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [refreshing,setRefreshing]=useState(false);
  const [search,setSearch]=useState("");
  const load=async()=>{try{setLoading(true);setItems(await getDoctors())}catch(e:any){Alert.alert("Doctors",e?.response?.data?.message||"Unable to load doctors.")}finally{setLoading(false);setRefreshing(false)}};
  useFocusEffect(useCallback(()=>{load()},[]));
  const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
  const openAdd=()=>{setEditing(null);setForm({...initial,availableDays:[]});setShow(true)};
  const openEdit=(d:any)=>{setEditing(d);setForm({...initial,name:d.user?.name||d.name||"",email:d.user?.email||d.email||"",phone:d.user?.phone||d.phone||"",specialization:d.specialization||"",qualification:d.qualification||"",licenseNumber:d.licenseNumber||"",experience:String(d.experience??0),consultationFee:String(d.consultationFee??0),availableDays:Array.isArray(d.availableDays)?d.availableDays:[],startTime:d.availability?.startTime||"09:00",endTime:d.availability?.endTime||"17:00",department:d.department||"",bio:d.bio||""});setShow(true)};
  const toggleDay=(v:string)=>set("availableDays",form.availableDays.includes(v)?form.availableDays.filter((x:string)=>x!==v):[...form.availableDays,v]);
  const save=async()=>{if(!form.name.trim()||!form.email.trim()||!form.specialization.trim()||!form.qualification.trim()||!form.licenseNumber.trim()){Alert.alert("Validation","Name, email, specialization, qualification and license are required.");return}if(!editing&&!form.password){Alert.alert("Validation","Password is required for a new doctor.");return}try{setSaving(true);const p:any={name:form.name.trim(),email:form.email.trim(),phone:form.phone.trim(),specialization:form.specialization.trim(),qualification:form.qualification.trim(),licenseNumber:form.licenseNumber.trim(),experience:Number(form.experience||0),consultationFee:Number(form.consultationFee||0),availableDays:form.availableDays,availability:{startTime:form.startTime,endTime:form.endTime},department:form.department.trim(),bio:form.bio.trim()};if(!editing)p.password=form.password;editing?await updateDoctor(editing._id,p):await createDoctor(p);setShow(false);await load();Alert.alert("Success",editing?"Doctor updated successfully.":"Doctor added successfully.")}catch(e:any){Alert.alert("Doctor",e?.response?.data?.message||"Unable to save doctor.")}finally{setSaving(false)}};
  const status=async(d:any)=>{try{if(d.isActive===false)await restoreDoctor(d._id);else await deleteDoctor(d._id);await load()}catch(e:any){Alert.alert("Doctor",e?.response?.data?.message||"Unable to change status.")}};
  const filtered=items.filter(d=>`${d.user?.name||d.name||""} ${d.specialization||""} ${d.qualification||""} ${d.department||""}`.toLowerCase().includes(search.toLowerCase()));
  if(show)return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><Text style={s.title}>{editing?"Edit Doctor":"Add Doctor"}</Text><Text style={s.sub}>Professional profile</Text>
    {["name","email","phone","password","specialization","qualification","licenseNumber","experience","consultationFee","department","startTime","endTime"].map(k=><View style={s.field} key={k}><Text style={s.label}>{k==="licenseNumber"?"License Number":k.charAt(0).toUpperCase()+k.slice(1)}{["name","email","specialization","qualification","licenseNumber"].includes(k)?" *":""}</Text><TextInput secureTextEntry={k==="password"} keyboardType={["experience","consultationFee"].includes(k)?"numeric":"default"} value={form[k]} onChangeText={v=>set(k,v)} placeholder={k==="password"?"Minimum 6 characters":k} placeholderTextColor="#98A2B3" style={s.input}/></View>)}
    <Text style={s.label}>Available Days</Text><View style={s.days}>{days.map(([label,v])=><TouchableOpacity key={v} onPress={()=>toggleDay(v)} style={[s.day,form.availableDays.includes(v)&&s.dayOn]}><Text style={[s.dayText,form.availableDays.includes(v)&&s.dayTextOn]}>{label}</Text></TouchableOpacity>)}</View>
    <View style={s.field}><Text style={s.label}>Bio</Text><TextInput value={form.bio} onChangeText={v=>set("bio",v)} multiline style={[s.input,{height:90,textAlignVertical:"top"}]} placeholder="Doctor bio" placeholderTextColor="#98A2B3"/></View>
    <TouchableOpacity style={s.primary} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>{editing?"Update Doctor":"Create Doctor"}</Text>}</TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>setShow(false)}><Text style={s.secondaryText}>Cancel</Text></TouchableOpacity></ScrollView></KeyboardAvoidingView></SafeAreaView>;
  return <SafeAreaView style={s.safe}><View style={s.container}><View style={s.row}><View><Text style={s.title}>Doctors</Text><Text style={s.sub}>{filtered.length} doctors</Text></View><TouchableOpacity style={s.small} onPress={openAdd}><Text style={s.smallText}>+ Add</Text></TouchableOpacity></View><TextInput style={s.input} value={search} onChangeText={setSearch} placeholder="Search doctors..." placeholderTextColor="#98A2B3"/>{loading?<ActivityIndicator color="#315FEF" style={{marginTop:40}}/>:<FlatList data={filtered} keyExtractor={x=>x._id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load()}}/>} renderItem={({item})=><View style={s.card}><View style={s.avatar}><Text style={s.avatarText}>DR</Text></View><View style={{flex:1}}><Text style={s.cardTitle}>{item.user?.name||item.name||"Doctor"}</Text><Text style={s.muted}>{item.specialization||"Specialist"} • {item.qualification||"—"}</Text><Text style={s.muted}>{item.user?.phone||item.phone||"No phone"} • {item.isActive===false?"Inactive":"Active"}</Text></View><TouchableOpacity onPress={()=>openEdit(item)}><Text style={s.action}>Edit</Text></TouchableOpacity><TouchableOpacity onPress={()=>status(item)}><Text style={s.danger}>{item.isActive===false?"On":"Off"}</Text></TouchableOpacity></View>} ListEmptyComponent={<Text style={s.empty}>No doctors found.</Text>}/>}</View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F7FB"},container:{padding:18,paddingBottom:40,flexGrow:1},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:14},title:{fontSize:28,fontWeight:"900",color:"#172033"},sub:{fontSize:13,color:"#7B8798",marginTop:3},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E5EAF1",borderRadius:12,height:48,paddingHorizontal:14,color:"#172033",marginBottom:12},field:{marginBottom:12},label:{fontSize:12,fontWeight:"800",color:"#4B5565",marginBottom:6},small:{backgroundColor:"#315FEF",paddingHorizontal:16,paddingVertical:11,borderRadius:11},smallText:{color:"#fff",fontWeight:"900"},days:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:14},day:{paddingHorizontal:12,paddingVertical:9,borderRadius:10,backgroundColor:"#E9EDF4"},dayOn:{backgroundColor:"#315FEF"},dayText:{fontWeight:"800",color:"#475467"},dayTextOn:{color:"#fff"},primary:{height:50,borderRadius:12,backgroundColor:"#315FEF",alignItems:"center",justifyContent:"center",marginTop:8},primaryText:{color:"#fff",fontWeight:"900"},secondary:{height:50,borderRadius:12,backgroundColor:"#E9EDF4",alignItems:"center",justifyContent:"center",marginTop:10},secondaryText:{color:"#334155",fontWeight:"800"},card:{backgroundColor:"#fff",borderRadius:16,padding:14,marginBottom:10,flexDirection:"row",alignItems:"center",gap:8},avatar:{width:44,height:44,borderRadius:14,backgroundColor:"#E8EEFF",alignItems:"center",justifyContent:"center"},avatarText:{color:"#315FEF",fontWeight:"900"},cardTitle:{fontSize:15,fontWeight:"900",color:"#172033"},muted:{fontSize:11,color:"#7B8798",marginTop:3},action:{color:"#315FEF",fontWeight:"900",fontSize:12},danger:{color:"#D92D20",fontWeight:"900",fontSize:12},empty:{textAlign:"center",marginTop:40,color:"#7B8798"}})
