import React, { useCallback, useState } from "react";
import { ActivityIndicator, Alert, FlatList, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useFocusEffect } from "expo-router";
import { createExpense, getExpenses } from "../api/api";

const initial={category:"general",amount:"",description:"",vendor:"",paymentMethod:"cash",expenseDate:"",receiptNumber:"",notes:""};
export default function Expenses(){
 const [items,setItems]=useState<any[]>([]),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[form,setForm]=useState(initial);
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const load=async()=>{try{setLoading(true);setItems(await getExpenses())}catch(e:any){Alert.alert("Expenses",e?.response?.data?.message||"Unable to load expenses.")}finally{setLoading(false);setRefreshing(false)}};
 useFocusEffect(useCallback(()=>{load()},[]));
 const save=async()=>{if(!form.amount||Number(form.amount)<=0||!form.description.trim()){Alert.alert("Validation","Valid amount and description are required.");return}try{setSaving(true);await createExpense({...form,amount:Number(form.amount),description:form.description.trim(),vendor:form.vendor.trim(),expenseDate:form.expenseDate||undefined,receiptNumber:form.receiptNumber.trim(),notes:form.notes.trim()});setShow(false);setForm(initial);await load();Alert.alert("Success","Expense created successfully.")}catch(e:any){Alert.alert("Expense",e?.response?.data?.message||"Unable to create expense.")}finally{setSaving(false)}};
 if(show)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}><Text style={s.t}>Add Expense</Text><Text style={s.sub}>Clinic financial record</Text>{Object.keys(initial).map(k=><View key={k}><Text style={s.l}>{k.charAt(0).toUpperCase()+k.slice(1)}</Text><TextInput keyboardType={k==="amount"?"numeric":"default"} style={[s.i,k==="notes"&&{height:80}]} multiline={k==="notes"} value={(form as any)[k]} onChangeText={v=>set(k,v)} placeholder={k==="expenseDate"?"YYYY-MM-DD":k} placeholderTextColor="#98A2B3"/></View>)}<TouchableOpacity style={s.p} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.pt}>Add Expense</Text>}</TouchableOpacity><TouchableOpacity style={s.sec} onPress={()=>setShow(false)}><Text style={s.st}>Cancel</Text></TouchableOpacity></ScrollView></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.c}><View style={s.row}><View><Text style={s.t}>Expenses</Text><Text style={s.sub}>{items.length} expenses</Text></View><TouchableOpacity style={s.small} onPress={()=>setShow(true)}><Text style={s.pt}>+ Add</Text></TouchableOpacity></View>{loading?<ActivityIndicator color="#315FEF" style={{marginTop:40}}/>:<FlatList data={items} keyExtractor={x=>x._id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load()}}/>} renderItem={({item})=><View style={s.card}><Text style={s.ct}>{item.description||"Expense"}</Text><Text style={s.amount}>₹{Number(item.amount||0).toLocaleString("en-IN")}</Text><Text style={s.m}>{item.category||"General"} • {item.vendor||"No vendor"}</Text><Text style={s.m}>{item.expenseDate?String(item.expenseDate).slice(0,10):"—"} • {item.paymentMethod||"cash"}</Text></View>} ListEmptyComponent={<Text style={s.empty}>No expenses found.</Text>}/>}</View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F7FB"},c:{padding:18,paddingBottom:40,flexGrow:1},t:{fontSize:28,fontWeight:"900",color:"#172033"},sub:{fontSize:13,color:"#7B8798",marginBottom:15},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:15},l:{fontSize:12,fontWeight:"800",color:"#4B5565",marginTop:6,marginBottom:6},i:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E5EAF1",borderRadius:12,height:48,paddingHorizontal:14,color:"#172033",marginBottom:8},p:{height:50,borderRadius:12,backgroundColor:"#315FEF",alignItems:"center",justifyContent:"center",marginTop:10},pt:{color:"#fff",fontWeight:"900"},sec:{height:50,borderRadius:12,backgroundColor:"#E9EDF4",alignItems:"center",justifyContent:"center",marginTop:10},st:{color:"#334155",fontWeight:"800"},small:{backgroundColor:"#315FEF",paddingHorizontal:15,paddingVertical:11,borderRadius:11},card:{backgroundColor:"#fff",borderRadius:16,padding:15,marginBottom:10},ct:{fontSize:15,fontWeight:"900",color:"#172033"},m:{fontSize:12,color:"#7B8798",marginTop:4},amount:{fontSize:19,fontWeight:"900",color:"#172033",marginTop:6},empty:{textAlign:"center",marginTop:40,color:"#7B8798"}})
