import React, { useCallback, useState } from "react";
import { ActivityIndicator, Alert, FlatList, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useFocusEffect } from "expo-router";
import { addStock, createInventoryItem, deleteInventoryItem, getInventory, removeStock } from "../api/api";

const initial={name:"",category:"",description:"",manufacturer:"",supplier:"",batchNumber:"",expiryDate:"",purchasePrice:"0",sellingPrice:"0",quantity:"0",unit:"piece",reorderLevel:"0",location:"",notes:""};
export default function Inventory(){
 const [items,setItems]=useState<any[]>([]),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[form,setForm]=useState(initial),[stock,setStock]=useState<any>(null),[amount,setAmount]=useState("");
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const load=async()=>{try{setLoading(true);setItems(await getInventory())}catch(e:any){Alert.alert("Inventory",e?.response?.data?.message||"Unable to load inventory.")}finally{setLoading(false);setRefreshing(false)}};
 useFocusEffect(useCallback(()=>{load()},[]));
 const save=async()=>{if(!form.name.trim()||!form.category.trim()){Alert.alert("Validation","Item name and category are required.");return}try{setSaving(true);await createInventoryItem({name:form.name.trim(),category:form.category.trim(),description:form.description.trim(),manufacturer:form.manufacturer.trim(),supplier:form.supplier.trim(),batchNumber:form.batchNumber.trim(),expiryDate:form.expiryDate||undefined,purchasePrice:Number(form.purchasePrice||0),sellingPrice:Number(form.sellingPrice||0),quantity:Number(form.quantity||0),unit:form.unit.trim()||"piece",reorderLevel:Number(form.reorderLevel||0),location:form.location.trim(),notes:form.notes.trim()});setShow(false);setForm(initial);await load();Alert.alert("Success","Inventory item created successfully.")}catch(e:any){Alert.alert("Inventory",e?.response?.data?.message||"Unable to create item.")}finally{setSaving(false)}};
 const stockUpdate=async(type:"add"|"remove")=>{const n=Number(amount);if(!n||n<=0)return Alert.alert("Validation","Enter a positive quantity.");try{if(type==="add")await addStock(stock._id,n);else await removeStock(stock._id,n);setStock(null);setAmount("");await load()}catch(e:any){Alert.alert("Stock",e?.response?.data?.message||"Unable to update stock.")}};
 const deactivate=(x:any)=>Alert.alert("Deactivate",`Deactivate ${x.name}?`,[{text:"Cancel",style:"cancel"},{text:"Deactivate",style:"destructive",onPress:async()=>{try{await deleteInventoryItem(x._id);await load()}catch(e:any){Alert.alert("Error",e?.response?.data?.message||"Unable to deactivate.")}}}]);
 if(show)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}><Text style={s.t}>Add Inventory Item</Text><Text style={s.sub}>Medicine and stock management</Text>{Object.keys(initial).map(k=><View key={k}><Text style={s.l}>{k.charAt(0).toUpperCase()+k.slice(1)}</Text><TextInput keyboardType={["purchasePrice","sellingPrice","quantity","reorderLevel"].includes(k)?"numeric":"default"} style={[s.i,["description","notes"].includes(k)&&{height:80}]} multiline={["description","notes"].includes(k)} value={(form as any)[k]} onChangeText={v=>set(k,v)} placeholder={k} placeholderTextColor="#98A2B3"/></View>)}<TouchableOpacity style={s.p} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.pt}>Create Item</Text>}</TouchableOpacity><TouchableOpacity style={s.sec} onPress={()=>setShow(false)}><Text style={s.st}>Cancel</Text></TouchableOpacity></ScrollView></SafeAreaView>;
 if(stock)return <SafeAreaView style={s.safe}><View style={s.c}><Text style={s.t}>{stock.name}</Text><Text style={s.sub}>Current stock: {stock.quantity||0} {stock.unit||"piece"}</Text><Text style={s.l}>Quantity</Text><TextInput style={s.i} keyboardType="numeric" value={amount} onChangeText={setAmount} placeholder="Enter quantity" placeholderTextColor="#98A2B3"/><TouchableOpacity style={s.p} onPress={()=>stockUpdate("add")}><Text style={s.pt}>Add Stock</Text></TouchableOpacity><TouchableOpacity style={s.remove} onPress={()=>stockUpdate("remove")}><Text style={s.removeText}>Remove Stock</Text></TouchableOpacity><TouchableOpacity style={s.sec} onPress={()=>setStock(null)}><Text style={s.st}>Cancel</Text></TouchableOpacity></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.c}><View style={s.row}><View><Text style={s.t}>Inventory</Text><Text style={s.sub}>{items.length} items</Text></View><TouchableOpacity style={s.small} onPress={()=>setShow(true)}><Text style={s.pt}>+ Add</Text></TouchableOpacity></View>{loading?<ActivityIndicator color="#315FEF" style={{marginTop:40}}/>:<FlatList data={items} keyExtractor={x=>x._id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load()}}/>} renderItem={({item})=><View style={s.card}><Text style={s.ct}>{item.name}</Text><Text style={s.m}>{item.category} • {item.supplier||"No supplier"}</Text><Text style={s.amount}>{item.quantity??0} {item.unit||"piece"}</Text><View style={s.actions}><TouchableOpacity onPress={()=>setStock(item)}><Text style={s.action}>Stock</Text></TouchableOpacity><TouchableOpacity onPress={()=>deactivate(item)}><Text style={s.danger}>Off</Text></TouchableOpacity></View></View>} ListEmptyComponent={<Text style={s.empty}>No inventory items found.</Text>}/>}</View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F7FB"},c:{padding:18,paddingBottom:40,flexGrow:1},t:{fontSize:28,fontWeight:"900",color:"#172033"},sub:{fontSize:13,color:"#7B8798",marginBottom:15},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:15},l:{fontSize:12,fontWeight:"800",color:"#4B5565",marginTop:6,marginBottom:6},i:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E5EAF1",borderRadius:12,height:48,paddingHorizontal:14,color:"#172033",marginBottom:8},p:{height:50,borderRadius:12,backgroundColor:"#315FEF",alignItems:"center",justifyContent:"center",marginTop:10},pt:{color:"#fff",fontWeight:"900"},sec:{height:50,borderRadius:12,backgroundColor:"#E9EDF4",alignItems:"center",justifyContent:"center",marginTop:10},st:{color:"#334155",fontWeight:"800"},remove:{height:50,borderRadius:12,backgroundColor:"#FDECEC",alignItems:"center",justifyContent:"center",marginTop:10},removeText:{color:"#D92D20",fontWeight:"900"},small:{backgroundColor:"#315FEF",paddingHorizontal:15,paddingVertical:11,borderRadius:11},card:{backgroundColor:"#fff",borderRadius:16,padding:15,marginBottom:10},ct:{fontSize:15,fontWeight:"900",color:"#172033"},m:{fontSize:12,color:"#7B8798",marginTop:4},amount:{fontSize:19,fontWeight:"900",color:"#172033",marginTop:7},actions:{flexDirection:"row",gap:18,marginTop:9},action:{color:"#315FEF",fontWeight:"900"},danger:{color:"#D92D20",fontWeight:"900"},empty:{textAlign:"center",marginTop:40,color:"#7B8798"}})
