import React, { useCallback, useState } from "react";
import PatientPortalSection from "../components/PatientPortalSection";
import { useAuth } from "../context/AuthContext";

import { ActivityIndicator, Alert, FlatList, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useFocusEffect } from "expo-router";
import { createPrescription, getAppointments, getDoctors, getMedicalRecords, getPatients, getPrescriptions } from "../api/api";

function Prescriptions(){
 const [items,setItems]=useState<any[]>([]),[patients,setPatients]=useState<any[]>([]),[doctors,setDoctors]=useState<any[]>([]),[appointments,setAppointments]=useState<any[]>([]),[records,setRecords]=useState<any[]>([]);
 const [show,setShow]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);
 const [form,setForm]=useState({patient:"",doctor:"",appointment:"",medicalRecord:"",prescriptionDate:"",medicine:"",dosage:"",frequency:"",duration:"",route:"Oral",instructions:"",generalInstructions:"",advice:"",followUpDate:""});
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const load=async()=>{try{setLoading(true);const [r,p,d,a,m]=await Promise.all([getPrescriptions(),getPatients(),getDoctors(),getAppointments(),getMedicalRecords()]);setItems(r);setPatients(p);setDoctors(d);setAppointments(a);setRecords(m)}catch(e:any){Alert.alert("Prescriptions",e?.response?.data?.message||"Unable to load prescriptions.")}finally{setLoading(false);setRefreshing(false)}};
 useFocusEffect(useCallback(()=>{load()},[]));
 const save=async()=>{if(!form.patient||!form.doctor||!form.appointment||!form.medicalRecord||!form.medicine.trim()||!form.dosage.trim()||!form.frequency.trim()||!form.duration.trim()){Alert.alert("Validation","Patient, doctor, appointment, medical record and medicine details are required.");return}try{setSaving(true);await createPrescription({patient:form.patient,doctor:form.doctor,appointment:form.appointment,medicalRecord:form.medicalRecord,prescriptionDate:form.prescriptionDate||undefined,medicines:[{name:form.medicine.trim(),dosage:form.dosage.trim(),frequency:form.frequency.trim(),duration:form.duration.trim(),route:form.route.trim()||"Oral",instructions:form.instructions.trim()}],generalInstructions:form.generalInstructions.trim(),advice:form.advice.trim(),followUpDate:form.followUpDate||undefined});setShow(false);await load();Alert.alert("Success","Prescription created successfully.")}catch(e:any){Alert.alert("Prescription",e?.response?.data?.message||"Unable to create prescription.")}finally{setSaving(false)}};
 if(show)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}><Text style={s.t}>New Prescription</Text><Text style={s.sub}>Digital prescription</Text>{["patient","doctor","appointment","medicalRecord","prescriptionDate","medicine","dosage","frequency","duration","route","instructions","generalInstructions","advice","followUpDate"].map(k=><View key={k}><Text style={s.l}>{k.charAt(0).toUpperCase()+k.slice(1)}</Text><TextInput style={[s.i,["instructions","generalInstructions","advice"].includes(k)&&{height:80}]} multiline={["instructions","generalInstructions","advice"].includes(k)} value={(form as any)[k]} onChangeText={v=>set(k,v)} placeholder={["patient","doctor","appointment","medicalRecord"].includes(k)?"Paste ID":k.includes("Date")?"YYYY-MM-DD":k} placeholderTextColor="#98A2B3"/></View>)}<Text style={s.hint}>{patients.length} patients • {doctors.length} doctors • {appointments.length} appointments • {records.length} records loaded.</Text><TouchableOpacity style={s.p} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.pt}>Create Prescription</Text>}</TouchableOpacity><TouchableOpacity style={s.sec} onPress={()=>setShow(false)}><Text style={s.st}>Cancel</Text></TouchableOpacity></ScrollView></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.c}><View style={s.row}><View><Text style={s.t}>Prescriptions</Text><Text style={s.sub}>{items.length} prescriptions</Text></View><TouchableOpacity style={s.small} onPress={()=>setShow(true)}><Text style={s.pt}>+ New</Text></TouchableOpacity></View>{loading?<ActivityIndicator color="#315FEF" style={{marginTop:40}}/>:<FlatList data={items} keyExtractor={x=>x._id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load()}}/>} renderItem={({item})=><View style={s.card}><Text style={s.ct}>{item.patient?.name||"Patient"}</Text><Text style={s.m}>{item.doctor?.user?.name||item.doctor?.name||"Doctor"}</Text><Text style={s.m}>{Array.isArray(item.medicines)?item.medicines.map((m:any)=>m.name).join(", "):"No medicines"}</Text><Text style={s.m}>{item.prescriptionDate?String(item.prescriptionDate).slice(0,10):"—"}</Text></View>} ListEmptyComponent={<Text style={s.empty}>No prescriptions found.</Text>}/>}</View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F7FB"},c:{padding:18,paddingBottom:40,flexGrow:1},t:{fontSize:28,fontWeight:"900",color:"#172033"},sub:{fontSize:13,color:"#7B8798",marginBottom:15},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:15},l:{fontSize:12,fontWeight:"800",color:"#4B5565",marginTop:6,marginBottom:6},i:{backgroundColor:"#fff",borderWidth:1,borderColor:"#E5EAF1",borderRadius:12,height:48,paddingHorizontal:14,color:"#172033",marginBottom:8},hint:{fontSize:11,color:"#7B8798",marginVertical:8},p:{height:50,borderRadius:12,backgroundColor:"#315FEF",alignItems:"center",justifyContent:"center",marginTop:10},pt:{color:"#fff",fontWeight:"900"},sec:{height:50,borderRadius:12,backgroundColor:"#E9EDF4",alignItems:"center",justifyContent:"center",marginTop:10},st:{color:"#334155",fontWeight:"800"},small:{backgroundColor:"#315FEF",paddingHorizontal:15,paddingVertical:11,borderRadius:11},card:{backgroundColor:"#fff",borderRadius:16,padding:15,marginBottom:10},ct:{fontSize:15,fontWeight:"900",color:"#172033"},m:{fontSize:12,color:"#7B8798",marginTop:4},empty:{textAlign:"center",marginTop:40,color:"#7B8798"}})


export default function PrescriptionsScreen() {
  const role = useAuthRole();
  if (role === "patient") return <PatientPortalSection section="prescriptions" />;
  return <Prescriptions />;
}

function useAuthRole() {
  const { user } = useAuth();
  return String(user?.role || "").toLowerCase();
}
