import React from "react";
import { SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import { ShieldCheck, Stethoscope, Users, UserRound, ArrowRight } from "lucide-react-native";

const C={navy:"#0B1736",blue:"#315FEF",bg:"#F5F7FB",white:"#fff",text:"#172033",muted:"#7B8798",border:"#E5EAF1",soft:"#E8EEFF"};
const roles=[
 {id:"patient",title:"Patient",description:"Create your account, book appointments and manage your health records, prescriptions and bills.",icon:UserRound,signup:true},
 {id:"doctor",title:"Doctor",description:"Sign in to manage appointments, patients, medical records and prescriptions.",icon:Stethoscope},
 {id:"receptionist",title:"Staff",description:"Sign in to manage reception, appointments, billing and clinic operations.",icon:Users},
 {id:"admin",title:"Admin",description:"Sign in to manage your clinic, users, operations, reports and system settings.",icon:ShieldCheck},
];
export default function RoleSelection(){const router=useRouter();return <SafeAreaView style={s.safe}><StatusBar barStyle="dark-content" backgroundColor={C.bg}/><ScrollView contentContainerStyle={s.page}>
 <View style={s.brandRow}><View style={s.logo}><Text style={s.plus}>+</Text></View><View><Text style={s.brand}>CareSync</Text><Text style={s.brandSub}>CLINIC MANAGEMENT</Text></View></View>
 <View style={s.heading}><Text style={s.eyebrow}>SECURE CLINIC PORTAL</Text><Text style={s.title}>Welcome to CareSync</Text><Text style={s.subtitle}>Choose how you would like to continue. Patients can create a new account, while clinic staff can sign in with their registered credentials.</Text></View>
 <View style={s.grid}>{roles.map(r=>{const Icon=r.icon;return <TouchableOpacity key={r.id} style={s.card} activeOpacity={.88} onPress={()=>r.id==="patient"?router.push("/patient-register"):router.push({pathname:"/login",params:{role:r.id}})}><View style={s.cardTop}><View style={s.icon}><Icon size={23} color={C.blue}/></View><ArrowRight size={18} color={C.muted}/></View><Text style={s.cardTitle}>{r.title}</Text><Text style={s.cardDesc}>{r.description}</Text><View style={s.action}><Text style={s.actionText}>{r.signup?"Create Patient Account":`Sign in as ${r.title}`}</Text></View></TouchableOpacity>})}</View>
 <View style={s.security}><ShieldCheck size={17} color={C.blue}/><Text style={s.securityText}>Your access is verified securely against your registered account and permissions.</Text></View><Text style={s.footer}>© {new Date().getFullYear()} CareSync • Secure Clinic Management</Text>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},page:{padding:20,paddingBottom:35},brandRow:{flexDirection:'row',alignItems:'center',gap:10,marginTop:12},logo:{width:42,height:42,borderRadius:13,backgroundColor:C.blue,alignItems:'center',justifyContent:'center'},plus:{fontSize:28,fontWeight:'900',color:C.white},brand:{fontSize:20,fontWeight:'900',color:C.text},brandSub:{fontSize:9,fontWeight:'800',letterSpacing:1.2,color:C.muted},heading:{marginTop:32,marginBottom:20},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:C.blue},title:{fontSize:30,fontWeight:'900',color:C.text,marginTop:6},subtitle:{fontSize:13,lineHeight:20,color:C.muted,marginTop:7},grid:{gap:12},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.border,borderRadius:18,padding:17},cardTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},icon:{width:48,height:48,borderRadius:15,backgroundColor:C.soft,alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:18,fontWeight:'900',color:C.text,marginTop:14},cardDesc:{fontSize:12,lineHeight:18,color:C.muted,marginTop:5},action:{marginTop:14,borderTopWidth:1,borderTopColor:C.border,paddingTop:12},actionText:{fontSize:12,fontWeight:'900',color:C.blue},security:{marginTop:18,backgroundColor:'#EEF4FF',borderRadius:13,padding:13,flexDirection:'row',gap:8,alignItems:'center'},securityText:{flex:1,fontSize:11,lineHeight:16,color:'#516174'},footer:{fontSize:11,color:C.muted,textAlign:'center',marginTop:18}});
